### PR TITLE
v1.0.0 Boards Manager install support

### PR DESCRIPTION
**Pull request by per1234**
Temporary Boards Manager URL for testing: https://raw.githubusercontent.com/per1234/MicroCore/bmtest/package_MCUdude_MicroCore_index.json

clipboard01

### CODE REVIEW

**Comment by per1234** [comment]
Currently the Boards Manager entries for all your cores have the **More info** link which points to the repository. There is also the option to add another link to the entry, **Online help**. If you want I can add this link and make it point to the Arduino Forum thread for each core.

**Comment by MCUdude** [comment]
Adding a link to the forum post would be awesome! Should I wait until you add this to the JSON file?

**Comment by MCUdude** [comment]
BTW I rolled back the v1.0.0 release, because I found an issue (micros() where enabled by default, and this causes serious overhead). I've also added the INPUT_PULLUP option. Do you have to do any changes to this pull request to include the "new" v1.0.0 release?

**Comment by per1234** [comment]
Ok, I've added the "Online help" link and also updated the test branch. I squashed the change into a single commit to keep the commit history clean.

I'll submit pull requests to the other repositories to add the "Online help" links.

I'll update this PR for the new 1.0.0 release and let you know as soon as that's done.

**Comment by MCUdude** [comment]
Thanks! I've added this core to the [Arduino on other Atmel chips](http://playground.arduino.cc/Main/ArduinoOnOtherAtmelChips) wiki page. We've discussed this before, but I think it's time to delete the old attiny13 link, which is a four year old article on how to add the core to Arduino 1.0. also the **ATtiny25/45/85/24/44/84 2313/4313 Alternative - works with 2k chips** link is kinda outdated, and is basically replaced with Dr. Azzys ATtinyCore.

**Comment by per1234** [comment]
I've updated to the new 1.0.0 release and also updated the test branch.

Do you want me to add MicroCore to https://github.com/arduino/Arduino/wiki/Unofficial-list-of-3rd-party-boards-support-urls?

I still have the edits to the Playground page on my "to do" list but haven't gotten to it yet. I think the IDE 1.6.10 release happened right after we had discussed that and I got distracted but I'll try to make it a priority to look over that page and clean it up a bit.

**Comment by MCUdude** [comment]
> Do you want me to add MicroCore to https://github.com/arduino/Arduino/wiki/Unofficial-list-of-3rd-party-boards-support-urls?

I totally forgot that page! Great if you bother to to it 😃

**Pull request merged**
