### PR TITLE
Add Boards Manager installation support for v1.0.2

### PR DESCRIPTION
**Pull request by per1234**
Temporary Boards Manager URL for testing:
https://raw.githubusercontent.com/per1234/MicroCore/bmtest/package_MCUdude_MicroCore_index.json

### CODE REVIEW

**Comment by MCUdude** [comment]
Great work as always. Thanks Per!

Oh, have you received your board yet?

**Comment by per1234** [comment]
You're very welcome!

No sign of my MightyBoard yet but I'm anxiously awaiting it. I've been doing some testing work on another project with ATmega1284P lately and was thinking how nice it will be to not have to deal with the breadboarded mess I usually use.

**Comment by MCUdude** [comment]
I'm currently waiting for some PCBs for my new MegaBoard dev board. It you want I can send you a PCB with the SMD components reflowed and an ATmega128 module you can insert into it 🙂 I got an Altium Designer license at work, so my new board are looking much nicer than the one that where made with Eagle. Development time is much quicker too!

megaboard_bottom
megaboard_top

**Comment by per1234** [comment]
Wow, that looks like a really nice board! Is it set up for the MCU on a daughterboard? I definitely need a MegaBoard. I'm limited in my testing abilities by the hardware I have on hand. I've been trying to help with this SD card bootloader project, avr_boot, for a while now and we claim to support ATmega1281, ATmega128, ATmega64 but nobody has actually tried it. Someone's been adding serial upload support to it in the last few days but they haven't wanted to add code for hardware we can't test, which is limiting us to 3 or 4 chips.

That's cool you get to play with Altium. I probably wouldn't be able to tell the difference in boards from Eagle vs. Altium. I have messed around with Kicad some but have yet to actually get one of my boards made. I make due with stripboard but I have several upcoming projects that will need multiple identical boards so for those I think it will end up being more efficient for me to design the PCBs and have them manufactured.

**Comment by MCUdude** [comment]
Yes, there's daughterboards that goes on top.


I've been wiring these modules to a MightyBoard without microcontroller, but I'm really looking forward to a proper dev board. I'm just happy to know that the boards gets in good hands, and actually being used for development.

(You never know, I might slip in some other cool stuff into the package, like my old ATtiny dev board I never bothered to sell. Works great with ATtiny13)

**Comment by per1234** [comment]
Sweet! I like the daughterboard system. That would be very much appreciated.

**Pull request merged**
